project:
  type: website
  output-dir: docs

website:
  title: "Spotify Me Een Klap Papa - Saison 25-26"
  navbar:
    logo: images/adaptive-icon.png
    left:
      - href: index.qmd
        text: Merci Antoine !!!
      - href: podiums.qmd
        text: Liste des Prix
      - href: winner.qmd
        text: Le Gagnant des gagnants
    right:
      - icon: github
        href: https://github.com/AlexandreGareau/Music-League-Podiums
        aria-label: GitHub

format:
  html:
    theme: vapor
    smooth-scroll: true
    echo: false

editor: visual

